### ISSUE TITLE
Clustering Map Pins

### ISSUE THREAD

**Issue by Smartcop** [MIT-Mobile/MIT-Mobile-for-iOS#879]
- [x] Clustering Pins - Add paging/swiping to detail screen #877
- [x] Clustering Pins - Redo search result cells #914
- [x] Clustering Pins - Redo map callout #915
- [x] Clustering Pins - Using rooms instead of machines for pins #916

**Comment by Smartcop** [comment]
:+1:
