### ISSUE TITLE
Image Gallery

### ISSUE THREAD

**Issue by mark-novak** [MIT-Mobile/MIT-Mobile-for-iOS#907]
- [ ] Image Gallery - Add header view with image #906
- [ ] Image Gallery - Update the data model to provide images #905 
- [ ] Image Gallery - Adding image to the gallery code #904 
- [ ] Image Gallery - Refactor news gallery #903

**Comment by justinanderson** [comment]
Resolved by #956.
