### ISSUE TITLE
Hours

### ISSUE THREAD

**Issue by Smartcop** [MIT-Mobile/MIT-Mobile-for-iOS#912]
- [x] Hours - Update data model #909
- [x] Hours - Make weekly hours use real data #910
- [x] Hours - Add summary hours to search results #911

**Comment by Smartcop** [comment]
:+1:
