### ISSUE TITLE
Advanced Search

### ISSUE THREAD

**Issue by mark-novak** [MIT-Mobile/MIT-Mobile-for-iOS#926]
- [x] Advanced Search - horizontal scrolling filter summary #919
- [x] Advanced Search - Update root screen #920
- [ ] ~~Advanced Search - tokenization (red text) #921~~
- [x] Advanced Search - Accordion View #922
- [x] Advanced Search - Add advanced search to recent #923
- [x] Advanced Search - Update data model with attributes #924
- [x] Advanced Search - Browse from root view #925

**Comment by bskinner** [comment]
#921 has been pushed off to a future release.
